---
title: "Multiple Pages"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    navbar:
      - { title: "About", href: "https://www.naver.com/", align: right } 
      - { icon: "fa-pencil", href: "https://www.github.com/", align: right}
---

Pag1 1
==========================================

This is an example. As you can see, flexdashboard can have text annotations.

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(knitr)
```

Column 1
-----------------------------------------------------------------------

### Gauge ex1. Contact Rate

```{r}
gauge(45, min=0, max=100, symbol = '%',              #전달되는 값에 따라서 색상을 변경시키라는 의미
      sectors = gaugeSectors(success = c(80, 100),
                             warning = c(40, 79),
                             danger = c(0, 39)))

```

### Gauge ex2. Average Rating

```{r}
rating=42
gauge(rating, 0, 50, label = 'Test', gaugeSectors(
  success = c(41, 50), warning = c(21, 40), danger = c(0, 20)))

```

### Text Annotation

One of the dashboard section can be as a text area.
Markdown Grammers can be helpful here.
It is not that difficult.
Just have a try

Column 2
-----------------------------------------------------------------------

Page2 {data-orientation=rows}
==================================================

### ggplot2 chart1

```{r}
ggplot(data=mtcars, aes(x=hp, y=mpg, color=as.factor(cyl)))+
  geom_point() +
  theme(legend.position = "blank")
```

