---
title: "Guage, navigation Bar & text Annotation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    navbar:
      - { title: "About", href: "https://www.naver.com/", align: right } # 글자로하려면 타이틀
      - { icon: "fa-pencil", href: "https://www.github.com/", align: right} # 그림으로 하려면 아이콘 속성
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(knitr)
```

Row1
-----------------------------------------------------------------------

### valuebox Example1

```{r}

valueBox(42, 
         icon = "fa-github")
```

### # of Bit Coin

```{r}
num = 8
valueBox(num,
         icon = "fa-bitcoin",
         color = "info")
```

### valuebox Example3

```{r}
num = 50
valueBox(num,
         caption="APPLE PAY",
         icon = "fa-bluetooth",
         color = ifelse(num>10, "warning", "primary")) # 워닝,프라이머리는 내장 상수(값을 10 미만으로 하면 색이 바뀜)
```

### valuebox Example4

```{r}
valueBox(107,
         caption="AWS",
         icon = "fa-cannabis",
         color = "success")
```

Row2
-----------------------------------

### ggplot2 graph

```{r}
ggplot(data=mtcars)+
  geom_bar(mapping = aes(x=cyl, fill=as.factor(am)),
           position="dodge")+
  theme(legend.position = "blank")
```

### Tabular data

```{r}
kable(mtcars)
```



















