---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
#https://rmarkdown.rstudio.com/flexdashboard/using.html#compenents
#html widgets의 최대 단점이 데이터셋을 모두 임베디드한다.(얘를 쓰면 모든 데이터를 다 가져오게 되어서 용량에서 손해)

library(flexdashboard)
library(dygraphs) # 시계열 자료에 대한 시각화 그래프 구현할 때, 하이라이트, 줌 등의 기능을 제공한다.
library(plotly) # ggplot2를 인터랙티브한 웹 버전으로 변환해주는 패키지

#install.packages("highcharter")
library(highcharter)
```

### Lung Deaths (All)

```{r}
dygraph(ldeaths)
```

### Lung Deaths (Male)

```{r}
dygraph(mdeaths)
```

### Lung Deathhs (Female)

```{r}
dygraph(fdeaths)
```

### Lung Deaths (all, plotly)

```{r}
plot_ly(mtcars, x=~hp, y=~mpg, type='scatter', mode='markers', color=~as.factor(cyl))
```

### Lung Deaths (Male, hchart)

```{r}
hchart(mtcars, "scatter", hcaes(x=hp, y=mpg, group = as.factor(cyl)))
```

### Lung Deaths (Female, hchart)

```{r}
hchart(diamonds$price, color="#B71C1C", name="Price") %>% 
  hc_title(text = "You can Zoom me")
```